name: CRM CI

on:
  push:
    branches: [ "main", "develop", "rc/*" ]
  pull_request:
    branches: [ "main", "develop", "rc/*" ]

env:
  REGISTRY: ghcr.io/flavien-hugs

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pipenv'

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv --python 3.10
        pipenv install --dev

    - name: Run Black
      run: pipenv run black . --check

    - name: Run Isort
      run: pipenv run isort . --check-only

    - name: Run Flake8
      run: pipenv run flake8 . --max-line-length=170 --ignore=E203,E266,E501,W503

    - name: Run Tests
      run: |
        export FLASK_RUN_PORT=5000
        export FLASK_DEBUG=0
        pipenv run python -m unittest discover -s tests

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Compute Docker tag
      id: docker_tag
      run: |
        REF_NAME="${GITHUB_REF#refs/heads/}"
        if [ "$REF_NAME" = "main" ]; then
            TAG="latest"
        elif [ "$REF_NAME" = "develop" ]; then
            TAG="dev"
        elif [ "$REF_NAME" = "preprod" ]; then
            TAG="preprod"
        elif [[ "$REF_NAME" == rc/* ]]; then
            VERSION="${REF_NAME#rc/}"
            TAG="${VERSION}_RC"
        else
            echo "Branch $REF_NAME not eligible for Docker image"
            exit 0
        fi

        echo "tag=$TAG" >> "$GITHUB_OUTPUT"

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/app/venone-crm
        tags: |
            type=raw,value=${{ steps.docker_tag.outputs.tag }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  release:
    name: Create Release Tag
    runs-on: ubuntu-latest
    needs: [ build-and-push ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
            github_token: ${{ secrets.MY_GITHUB_TOKEN }}
            default_bump: patch
